Visualise the measurement data by Category and Nomenclature to start to understand how it could be useful in evaluating the use of NLP pipelines on GSS bond documentations for particular downstream tasks

After this, draw out the rough pipeline I'm thinking of

In [1]:
import pandas as pd
import matplotlib

In [15]:
cats_and_measures_data = pd.read_csv('Cats_and_measures.csv')
cats_and_measures_df = pd.DataFrame(cats_and_measures_data)
cats_and_measures_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 524 entries, 0 to 523
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unit          524 non-null    str
 1   Indicator     524 non-null    str
 2   Nomenclature  520 non-null    str
 3   Category      520 non-null    str
dtypes: str(4)
memory usage: 16.5 KB

In [16]:
cats_and_measures_df['Indicator'].nunique()

147

In [17]:
cats_and_measures_df.groupby('Nomenclature').count()

                                                 Unit  Indicator  Category
Nomenclature
Climate Bonds Initiative Project Classification   226        226       226
EU Taxonomy Green Bonds Standard                   41         41        41
ICMA Green Bonds Principles Project Categories    212        212       212
ISO                                                41         41        41

In [18]:
indicators_df = pd.DataFrame(cats_and_measures_df.groupby('Indicator').count())
indicators_df.sort_values('Category', ascending = False, inplace=True)
indicators_df

                               Unit  Nomenclature  Category
Indicator
tCO2e avoided                    29            29        29
tCO2e reduced                    28            28        28
MWh energy saving                14            14        14
t CO2e emissions                 13            13        13
% water saving                   12            12        12
...                             ...           ...       ...
% animals endangered              2             2         2
% SOx reduced                     2             2         2
dB noise level reduced            2             2         2
t TRS (total reduced sulphur)     1             0         0
t PM avoided/reduced              1             0         0

[147 rows x 3 columns]

In [19]:
indicators_df.describe()

             Unit  Nomenclature    Category
count  147.000000    147.000000  147.000000
mean     3.564626      3.537415    3.537415
std      3.760042      3.769510    3.769510
min      1.000000      0.000000    0.000000
25%      2.000000      2.000000    2.000000
50%      2.000000      2.000000    2.000000
75%      4.000000      4.000000    4.000000
max     29.000000     29.000000   29.000000

In [20]:
cats_and_measures_df['Category'].nunique()

51

In [21]:
categories_df = pd.DataFrame(cats_and_measures_df.groupby('Category').count())
categories_df.sort_values('Unit', ascending = False, inplace=True)
categories_df

                                      Unit  Indicator  Nomenclature
Category
Unspecified                            106        106           106
Treatment                               46         46            46
Wastewater treatment                    41         41            41
Ecosystem Conservation & Restoration    24         24            24
Natural landscapes                      21         21            21
Residential                             18         18            18
Bioenergy                               16         16            16
Transmission                            16         16            16
Appliances                              16         16            16
Forestry                                16         16            16
Generation                              14         14            14
Commercial Forestry                     14         14            14
Products & Systems for Efficiency       14         14            14
Infrastructure                          11         11            11
Wind                                    10         10            10
Packaging                               10         10            10
Reduction of local emissions            10         10            10
Commercial                              10         10            10
Products                                 9          9             9
Solar                                    7          7             7
Public                                   6          6             6
Storage                                  6          6             6
Agriculture                              6          6             6
Hydro                                    5          5             5
Early warning systems                    5          5             5
Recycling                                5          5             5
Preparation                              4          4             4
Greenhouse gas control                   4          4             4
Rail                                     4          4             4
Smart grids                              3          3             3
Reforestation                            3          3             3
Waste reduction                          3          3             3
Electric                                 3          3             3
Power Management                         3          3             3
Private                                  3          3             3
Grid                                     3          3             3
Distribution                             2          2             2
Reuse                                    2          2             2
Low Carbon Buses                         2          2             2
Flood defence                            2          2             2
Data hubs                                2          2             2
Flooding mitigation                      2          2             2
Urban Development                        2          2             2
Urban drainage                           2          2             2
Vehicle infrastructure                   2          2             2
Waste recycling                          2          2             2
Water-borne                              1          1             1
Freight Rail                             1          1             1
District heating                         1          1             1
Hybrid                                   1          1             1
Monitoring                               1          1             1

In [61]:
unspecified_cats = cats_and_measures_df.loc[cats_and_measures_df['Category']=='Unspecified']
unspec_cats_indicators = unspecified_cats.groupby('Indicator')
unspec_cats_indicators_df = pd.DataFrame(unspec_cats_indicators)
unspec_cats_indicators_df

,0,1
0,# complaints resolved,Unit Indicator \ 275 unit ...
1,# fauna species identified,Unit Indicator ...
2,# flora species identified,Unit Indicator ...
3,# green buildings certified,Unit Indicator ...
4,# microbasins conserved,Unit Indicator \ 273 uni...
5,# paper packaging trays used,Unit Indicator \ 246...
6,# research studies,Unit Indicator \ 330 unit # ...
7,# times less area planted,Unit Indicator \ 252 u...
8,% COD intensity avoided/reduced,Unit Indicator ...
9,% area conserved,Unit Indicator \ 277 percent...
10,% carbon sequestered,Unit Indicator \ 254 per...
11,% critical suppliers evaluated,Unit Indicator ...
12,% effluent treatment efficiency,Unit Indicator ...
13,% energy saving,Unit Indicator \ 256 percent ...
14,% raw material in packaging used,Unit Indicator...
15,% renewable energy used,Unit Indicator ...
16,% waste reduced,Unit Indicator ...
17,% wastewater collected,Unit Indicator ...
18,% wastewater treated,Unit Indicator ...
19,% water losses in distribution,Unit Indicator ...
20,% water recirculated/reused/replenish intensity,Unit ...
21,% water saving,Unit Indicator ...
22,Index Great Place to Work,Unit Indicator ...
23,MW installed capacity,Unit Indicator ...
24,MWh energy generated,Unit Indicator ...
25,MWh energy saving,Unit Indicator \ 98 ...
26,MWh renewable energy generation,Unit Indic...
27,MWh renewable energy used,Unit Indicator ...
28,dayEq lost due to workplace injury,Unit Indicator ...
29,h training per full time equivalent,Unit Indicator...
30,ha additional area protected,Unit Indicator ...
31,ha area monitored,Unit Indicator \ 269 hectar...
32,ha area with restoration in progress,Unit Indic...
33,ha microbasins conserved,Unit Indicator \ 271 ...
34,ha reforested,Unit Indicator ...
35,ha total area recovered,Unit Indicator ...
36,kWh/m¬≥ energy consumption in wastewater treated,Unit \ 166 kil...
37,kWh/m¬≥ energy consumption in water treated,Unit \ 170 kil...
38,kg/1000m¬≥ chemicals consumption in wastewater...,Unit \ 158 kilogram...
39,kg/1000m¬≥ chemicals consumption in water treated,Unit \ 162 kilogram...
40,l/connection/day water losses,Unit Indicator ...
41,l/l water used,Unit Indicator ...
42,mg/l BOD intensity,Unit Indicator ...
43,mg/l COD intensity,Unit Indicator ...
44,m¬≤ green building area,Unit Indicator ...
45,m¬≥ water saved,Unit Indicator \ 390 cubi...
46,t CO2e emissions,Unit Indicator \ 107 metr...
47,t chemicals reduced,Unit Indicator \ 244 m...
48,t waste from landfill reduced,Unit Indicator...
49,tCO2e avoided,Unit Indicator \ 81 metric ...
50,tCO2e reduced,Unit Indicator \ 100 metric ...
51,tCO2e sequestered,Unit Indicator ...
52,¬µg/m¬≥ PM 10 level,Unit Indic...
53,¬µg/m¬≥ PM 2.5 level,Unit Indi...

In [54]:
unspec_cats_ind_set = set(unspecified_cats['Indicator'])
unspec_cats_ind_list = list(unspec_cats_ind_set)