In [5]:
pip install spacy

Requirement already satisfied: spacy in ./.venv/lib/python3.13/site-packages (3.8.14)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in ./.venv/lib/python3.13/site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in ./.venv/lib/python3.13/site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in ./.venv/lib/python3.13/site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in ./.venv/lib/python3.13/site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in ./.venv/lib/python3.13/site-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in ./.venv/lib/python3.13/site-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in ./.venv/lib/python3.13/site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in ./.venv/lib/python3.13/site-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in ./.venv/lib/python3.13/site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in ./.venv/lib/python3.13/site-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in ./.venv/lib/python3.13/site-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in ./.venv/lib/python3.13/site-packages (from spacy) (0.24.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in ./.venv/lib/python3.13/site-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in ./.venv/lib/python3.13/site-packages (from spacy) (2.4.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in ./.venv/lib/python3.13/site-packages (from spacy) (2.33.1)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in ./.venv/lib/python3.13/site-packages (from spacy) (2.13.0)
Requirement already satisfied: jinja2 in ./.venv/lib/python3.13/site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in ./.venv/lib/python3.13/site-packages (from spacy) (81.0.0)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.13/site-packages (from spacy) (26.0)
Requirement already satisfied: annotated-types>=0.6.0 in ./.venv/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.0 in ./.venv/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.46.0)
Requirement already satisfied: typing-extensions>=4.14.1 in ./.venv/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in ./.venv/lib/python3.13/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.13/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.13/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in ./.venv/lib/python3.13/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in ./.venv/lib/python3.13/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.2.25)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in ./.venv/lib/python3.13/site-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: click>=8.2.1 in ./.venv/lib/python3.13/site-packages (from typer<1.0.0,>=0.3.0->spacy) (8.3.2)
Requirement already satisfied: shellingham>=1.3.0 in ./.venv/lib/python3.13/site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in ./.venv/lib/python3.13/site-packages (from typer<1.0.0,>=0.3.0->spacy) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in ./.venv/lib/python3.13/site-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in ./.venv/lib/python3.13/site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.23.0)
Requirement already satisfied: smart-open>=5.2.1 in ./.venv/lib/python3.13/site-packages (from weasel<2.0.0,>=1.0.0->spacy) (7.6.0)
Requirement already satisfied: httpx>=0.24.0 in ./.venv/lib/python3.13/site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: anyio in ./.venv/lib/python3.13/site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.13.0)
Requirement already satisfied: httpcore==1.* in ./.venv/lib/python3.13/site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in ./.venv/lib/python3.13/site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in ./.venv/lib/python3.13/site-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in ./.venv/lib/python3.13/site-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in ./.venv/lib/python3.13/site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Requirement already satisfied: wrapt in ./.venv/lib/python3.13/site-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (2.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in ./.venv/lib/python3.13/site-packages (from jinja2->spacy) (3.0.3)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [1]:
# import libraries

import pymupdf
import spacy
import re
import pandas as pd
import numpy as np
#import unicodedata
import os
from pathlib import Path
from translate import Translator

In [4]:
!python3 -m spacy download es_core_news_lg

Collecting es-core-news-lg==3.8.0
  Downloading es_core_news_lg-3.8.0-py3-none-any.whl (568.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 568.0/568.0 MB 4.2 MB/s  0:02:080:00:0100:04

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
✔ Download and installation successful
You can now load the package via spacy.load('es_core_news_lg')

In [5]:
# nlp piplines from spacy for the 3 languages. large chosen for the higher dimension word vector libraries

nlp_en = spacy.load('en_core_web_lg')
nlp_pt = spacy.load('pt_core_news_lg')
nlp_es = spacy.load('es_core_news_lg')

In [6]:
# lists of green bond category words for usse in spacy similarity method 

all_cat_words_en = ['renewable', 'solar', 'wind', 'bioenergy', 'biofuel', 'biomass', 'hydropower', 'hydrogen',
                 'power', 'grid', 'transmission', 'generation', 'efficiency', 'retrofit', 'pollution', 'waste',
                 'land', 'agriculture', 'forestry', 'forest', 'fisheries', 'food', 'terrestrial', 'aquatic',
                   'biodiversity', 'conservation', 'transportation', 'electric', 'battery', 'EV', 'charger',
                     'bus', 'rail', 'train', 'car', 'vehicle', 'bicycle', 'non-motorized', 'aviation',
                     'water', 'potable', 'wastewater', 'sanitation', 'treatment', 'adaptation', 'disaster',
                     'circular', 'recycle', 'reuse','buildings', 'appliances', 'housing']

renewable_energy_en = ['renewable', 'solar', 'wind', 'bioenergy', 'biofuel', 'biomass', 'hydropower', 'hydrogen', 'power', 'grid', 'transmission', 'generation']
energy_efficiency_en = ['efficiency', 'retrofit']
pollution_prevention_and_control_en = ['pollution', 'waste']
environmentally_sustainable_management_of_living_natural_resources_and_land_use_en = ['land', 'agriculture', 'forestry', 'forest', 'fisheries', 'food']
terrestrial_and_aquatic_biodiversity_conservation_en = ['terrestrial', 'aquatic', 'biodiversity', 'conservation']
clean_transportation_en = ['transportation', 'electric', 'battery', 'EV', 'charger', 'bus', 'rail', 'train', 'car', 'vehicle', 'bicycle', 'non-motorized', 'aviation']
sustainable_water_and_wastewater_management_en = ['water', 'potable', 'wastewater', 'sanitation', 'treatment']
climate_change_adaptation_en = ['adaptation', 'disaster']
circular_economy_and_or_ecoefficient_projects_en = ['circular', 'recycle', 'reuse']
green_buildings_en = ['buildings', 'appliances', 'housing']

In [7]:
# iterate each word in the lists through the Translator from translate - English to Portuguese

all_cat_words_pt = []
renewable_energy_pt = []
energy_efficiency_pt = []
pollution_prevention_and_control_pt = []
environmentally_sustainable_management_of_living_natural_resources_and_land_use_pt = []
terrestrial_and_aquatic_biodiversity_conservation_pt = []
clean_transportation_pt = []
sustainable_water_and_wastewater_management_pt = []
climate_change_adaptation_pt = []
circular_economy_and_or_ecoefficient_projects_pt = []
green_buildings_pt = []


translator = Translator(to_lang='pt',from_lang='en')
for word in all_cat_words_en:
    translation = translator.translate(word)
    all_cat_words_pt.append(translation)
for word in renewable_energy_en:
    translation = translator.translate(word)
    renewable_energy_pt.append(translation)
for word in energy_efficiency_en:
    translation = translator.translate(word)
    energy_efficiency_pt.append(translation)
for word in pollution_prevention_and_control_en:
    translation = translator.translate(word)
    pollution_prevention_and_control_pt.append(translation)
for word in environmentally_sustainable_management_of_living_natural_resources_and_land_use_en:
    translation = translator.translate(word)
    environmentally_sustainable_management_of_living_natural_resources_and_land_use_pt.append(translation)
for word in terrestrial_and_aquatic_biodiversity_conservation_en:
    translation = translator.translate(word)
    terrestrial_and_aquatic_biodiversity_conservation_pt.append(translation)
for word in clean_transportation_en:
    translation = translator.translate(word)
    clean_transportation_pt.append(translation)
for word in sustainable_water_and_wastewater_management_en:
    translation = translator.translate(word)
    sustainable_water_and_wastewater_management_pt.append(translation)
for word in climate_change_adaptation_en:
    translation = translator.translate(word)
    climate_change_adaptation_pt.append(translation)
for word in circular_economy_and_or_ecoefficient_projects_en:
    translation = translator.translate(word)
    circular_economy_and_or_ecoefficient_projects_pt.append(translation)
for word in green_buildings_en:
    translation = translator.translate(word)
    green_buildings_pt.append(translation)

In [8]:
# iterate each word in the lists through the Translator from translate - English to Spanish

all_cat_words_es = []
renewable_energy_es = []
energy_efficiency_es = []
pollution_prevention_and_control_es = []
environmentally_sustainable_management_of_living_natural_resources_and_land_use_es = []
terrestrial_and_aquatic_biodiversity_conservation_es = []
clean_transportation_es = []
sustainable_water_and_wastewater_management_es = []
climate_change_adaptation_es = []
circular_economy_and_or_ecoefficient_projects_es = []
green_buildings_es = []


translator = Translator(to_lang='es',from_lang='en')
for word in all_cat_words_en:
    translation = translator.translate(word)
    all_cat_words_es.append(translation)
for word in renewable_energy_en:
    translation = translator.translate(word)
    renewable_energy_es.append(translation)
for word in energy_efficiency_en:
    translation = translator.translate(word)
    energy_efficiency_es.append(translation)
for word in pollution_prevention_and_control_en:
    translation = translator.translate(word)
    pollution_prevention_and_control_es.append(translation)
for word in environmentally_sustainable_management_of_living_natural_resources_and_land_use_en:
    translation = translator.translate(word)
    environmentally_sustainable_management_of_living_natural_resources_and_land_use_es.append(translation)
for word in terrestrial_and_aquatic_biodiversity_conservation_en:
    translation = translator.translate(word)
    terrestrial_and_aquatic_biodiversity_conservation_es.append(translation)
for word in clean_transportation_en:
    translation = translator.translate(word)
    clean_transportation_es.append(translation)
for word in sustainable_water_and_wastewater_management_en:
    translation = translator.translate(word)
    sustainable_water_and_wastewater_management_es.append(translation)
for word in climate_change_adaptation_en:
    translation = translator.translate(word)
    climate_change_adaptation_es.append(translation)
for word in circular_economy_and_or_ecoefficient_projects_en:
    translation = translator.translate(word)
    circular_economy_and_or_ecoefficient_projects_es.append(translation)
for word in green_buildings_en:
    translation = translator.translate(word)
    green_buildings_es.append(translation)

In [27]:
# find tables in the document and return table info

def catTable(document, tableStrategy):
    
    pdf = pymupdf.open(document) 
    filename = os.path.basename(document)

    tableCount = 0
    tablePages = []
    tableHeaders = []
    tableDFs = []


    for page_idx in range(len(pdf)): 
        page = pdf[page_idx]

        find_tables = page.find_tables(strategy = tableStrategy)
        if find_tables.tables:
            table_count = len(find_tables.tables)
            tableheader = find_tables[0].header.names # assume only 1 table per page
            tableDF = find_tables[0].to_pandas()
            tableCount += table_count
            tablePages.append(page_idx)
            tableHeaders.append(tableheader)
            tableDFs.append(tableDF)

    return filename, tableCount, tablePages, tableHeaders, tableDFs

In [26]:
# assess the tables found in the catTable function to idnetify the Category tables and extract unique list of Cateogries
# process the list using the spacy token.similarity function to clean up spurious elements

def tableAssess(language, tableCount, tablePages, tableHeaders, tableDFs):

    if language == 'PT':
        keywordsCAT = ['Categoria']
        nlp = nlp_pt
        all_cat_words = all_cat_words_pt
        cleanup_TH = 0.65
    elif language == 'ES':
        keywordsCAT = ['Categoría', 'Categorías']
        nlp = nlp_es
        all_cat_words = all_cat_words_es
        cleanup_TH = 0.65
    elif language == 'EN':
        keywordsCAT = ['Category', 'Categories', 'Criteria', 'Criterion']
        nlp = nlp_en
        all_cat_words = all_cat_words_en
        cleanup_TH = 0.65
    
    tablePageCurrent = 0
    tablePagePrior = 0
    tablepageCurrentTrue = 0
    uniqueCats = []
    uniqueCatsNoDupes = []
    table_idx = []

    all = all_cat_words
    CatwordsFinal = []
    simScores = {}

    if tableCount == 1: # applicable if only 1 table detected in whole pdf
        dataFrame = tableDFs[0]
        header = tableHeaders[0]
        for keyword in keywordsCAT:
            if keyword.lower() in header[0].lower(): # assumes category col is always the first (LHS) col
                colName = header[0]
                uniqueC = dataFrame[colName].dropna().unique().tolist()
                for messyCat in uniqueC:
                    if messyCat:
                        tidyCat = messyCat.replace('\n',' ').lower()
                        uniqueCatsNoDupes.append(tidyCat)
                        table_idx.append(0)
    elif tableCount > 1:
        for idx in range(len(tableDFs)): # count of tableHeaders and DFs should be the same, based on the page level find_tables object
            tablePageCurrent = tablePages[idx]
            dataFrame = tableDFs[idx]
            header = tableHeaders[idx]
            for keyword in keywordsCAT:
                if keyword.lower() in header[0].lower():
                    colName = header[0]
                    uniqueC = dataFrame[colName].dropna().unique().tolist()
                    tablepageCurrentTrue = tablePageCurrent
                    for messyCat in uniqueC:
                        if messyCat:
                            tidyCat = messyCat.replace('\n',' ').lower()
                            uniqueCats.append(tidyCat)
                            table_idx.append(idx)
                elif header[0] == 'Col0' and tablePageCurrent - tablepageCurrentTrue == 1: # the condition where the last keyword-compliant table processed was one page before the current table 
                    uniqueC = dataFrame['Col0'].dropna().unique().tolist()
                    if uniqueC:
                        for messyCat in uniqueC:
                            if messyCat:
                                tidyCat = messyCat.replace('\n',' ').lower()
                                uniqueCats.append(tidyCat)
                                table_idx.append(idx)
            tablePagePrior = tablePageCurrent
        uniqueCatsNoDupes = list(set(uniqueCats))

    if len(uniqueCatsNoDupes) > 0: 

        for cat in uniqueCatsNoDupes:
            docCat = nlp(cat)
            for wordx in all:
                docx = nlp(wordx)
                if docCat.similarity(docx) >= cleanup_TH:
                    CatwordsFinal.append(cat)
                    simScores[cat + ' ' + wordx] = docCat.similarity(docx)
                    dfsimScores = pd.DataFrame.from_dict(simScores, 'index')
                    CatwordsFFinal = list(set(CatwordsFinal))
    else:
        CatwordsFFinal = []
        dfsimScores = pd.DataFrame()

    return uniqueCatsNoDupes, table_idx, CatwordsFFinal, dfsimScores

In [28]:
# to find the Use of Proceeds portion of the document, returns font info for key phrases that typically indicate the start and end of that portion

def fontInfo(language, document):

    results_UOP = []
    results_SEEGP = []
    
    pdf = pymupdf.open(document)
    
    if language == 'PT':
        keywordsUOP = ['Usos dos Recursos', 'Uso de Recursos']
        keywordsSEEGP = ['Selection and Evaluation', 'Process for the Project Evaluation and Selection', 'Project Evaluation and Selection Process', 'Project Selection and Evaluation Process', 'Process for Project Evaluation and Selection', 'Project Selection and Assessment Process', 'Project Selection Criteria', 'Project evaluation & selection', 'Project Selection Process']
        keywordsSEEGP_test = ['Avaliação e Seleção de Ativos', 'Processo de Avaliação e Seleção de Projetos']
    elif language == 'ES':
        keywordsUOP = ['Uso de los Fondos', 'Uso de Fondos', 'Uso de Recursos', 'Destinos de Fondos', 'Uso de los Recursos']
        keywordsSEEGP_test = ['Proceso de Evaluación y Selección de Proyectos', 'Selección y Evaluación de Proyectos', 'Procedimiento Selección', 'Evaluación y selección de proyectos']
    elif language == 'EN':
        keywordsUOP = ['Use of Proceeds', 'Use of Funds', 'Use of the Proceeds']
        keywordsSEEGP = ['Selection and Evaluation', 'Process for the Project Evaluation and Selection', 'Project Evaluation and Selection Process', 'Project Selection and Evaluation Process', 'Process for Project Evaluation and Selection', 'Project Selection and Assessment Process', 'Project Selection Criteria', 'Project evaluation & selection', 'Project Selection Process']
        keywordsSEEGP_test = ['Selection and Evaluation', 'Process for', 'Evaluation and Selection', 'Project Evaluation', 'Assessment Process', 'Selection process', 'Project selection criteria']


    for page_idx in range(len(pdf)): 
        page = pdf[page_idx]
        dict = page.get_text("dict")
        blocks = dict["blocks"] 
        for block in blocks:
            if "lines" in block.keys():
                spans = block['lines']
                for span in spans:
                    data = span['spans']
                    for lines in data:
                        for keyword in keywordsUOP:
                            if keyword.lower() in lines['text'].lower().strip():
                                results_UOP.append((lines['text'], lines['size'], lines['bbox'], page_idx))
                        for keyword in keywordsSEEGP_test:
                            if keyword.lower() in lines['text'].lower().strip():
                                results_SEEGP.append((lines['text'], lines['size'], lines['bbox'], page_idx))

                            

    return results_UOP, results_SEEGP

In [29]:
# from the results of the previous function, returns the result index containing the highest font size, assuming this is a section header 

def find_max_font(results_UOP, results_SEEGP):
    
    max_font_size_UOP = 0
    for result_idx_UOP in range(len(results_UOP)):
        resultA = results_UOP[result_idx_UOP]
        if resultA[1] > max_font_size_UOP:
            max_font_size_UOP = resultA[1]
            max_idx_UOP = result_idx_UOP

    max_font_size_SEEGP = 0
    if len(results_SEEGP) == 0:
        max_idx_SEEGP = 0
    else:       
        for result_idx_SEEGP in range(len(results_SEEGP)):
            resultB = results_SEEGP[result_idx_SEEGP]
            if resultB[1] > max_font_size_SEEGP:
                max_font_size_SEEGP = resultB[1]
                max_idx_SEEGP = result_idx_SEEGP

    return max_idx_UOP, max_idx_SEEGP

In [30]:
# corrects the UOP portion in the cases where the functions above have returned the table of contents instances of the start and end key phrases 

def tocCheck(results_UOP, results_SEEGP, max_idx_UOP, max_idx_SEEGP):
    
    if len(results_SEEGP) == 0:
        areaUOP = results_UOP[max_idx_UOP]
        areaUOP_page = areaUOP[3]
        areaUOP_coords = areaUOP[2]
        areaUOP_y1 = areaUOP_coords[3]
        areaSEEGP_page = 0
        areaSEEGP_y0 = 0

    else:
        areaUOP = results_UOP[max_idx_UOP]
        areaSEEGP = results_SEEGP[max_idx_SEEGP]
        areaUOP_page = areaUOP[3]
        areaSEEGP_page = areaSEEGP[3]
        areaUOP_coords = areaUOP[2]
        areaSEEGP_coords = areaSEEGP[2]
        areaUOP_y1 = areaUOP_coords[3]
        areaSEEGP_y0 = areaSEEGP_coords[1]

        if areaUOP_page == areaSEEGP_page:
            if 0 < areaSEEGP_y0 - areaUOP_y1 < 40:
                results_UOP_remove = results_UOP.pop(max_idx_UOP)
                results_SEEGP_remove = results_SEEGP.pop(max_idx_SEEGP)

                max_idx_UOP, max_idx_SEEGP = find_max_font(results_UOP, results_SEEGP)

                areaUOP = results_UOP[max_idx_UOP]
                areaSEEGP = results_SEEGP[max_idx_SEEGP]
                areaUOP_page = areaUOP[3]
                areaSEEGP_page = areaSEEGP[3]
                areaUOP_coords = areaUOP[2]
                areaSEEGP_coords = areaSEEGP[2]
                areaUOP_y1 = areaUOP_coords[3]
                areaSEEGP_y0 = areaSEEGP_coords[1]

    return areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0

In [31]:
# discards the UOP end boundary in cases where it comes before the start boundary

def keepSEEGP(areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0):

    if areaSEEGP_page == areaUOP_page:
        if areaSEEGP_y0 < areaUOP_y1:
            keep_areaSEEGP = False
        elif areaSEEGP_y0 > areaUOP_y1:
            keep_areaSEEGP = True
    elif areaSEEGP_page > areaUOP_page:
        keep_areaSEEGP = True
    elif areaSEEGP_page < areaUOP_page:
        keep_areaSEEGP = False

    return keep_areaSEEGP

In [32]:
# page scenarios and extract words when keep_areaSEEGP = True
# function called by another function

def wordsUOP_endPage(document, areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0):

    pdf = pymupdf.open(document)
    extractUOPwords = []

    # iterate pages
    for page_idx in range(len(pdf)):
        page = pdf[page_idx]

       
# process four page scenarios and extract text as words
    # A: UOP all on a single page
        if page_idx == areaUOP_page and page_idx == areaSEEGP_page:
            for word in page.get_text('words'):
                x0, y0, x1, y1, messyText, *_ = word
                if y0 > areaUOP_y1 and y1 < areaSEEGP_y0:
                    tidyText = messyText.replace('\n',' ').lower()
                    extractUOPwords.append(tidyText)

    # UOP across >1 page
    # B: current page is start page
        elif page_idx == areaUOP_page:
            for word in page.get_text('words'):
                x0, y0, x1, y1, messyText, *_ = word
                if y0 > areaUOP_y1:
                    tidyText = messyText.replace('\n',' ').lower()
                    extractUOPwords.append(tidyText)

    # D: current page is neither start nor end page but is in the UOP area
        elif page_idx > areaUOP_page and page_idx < areaSEEGP_page:
            for word in page.get_text('words'):
                x0, y0, x1, y1, messyText, *_ = word
                tidyText = messyText.replace('\n',' ').lower()
                extractUOPwords.append(tidyText)

    # C: current page is end page
        elif page_idx == areaSEEGP_page:
                for word in page.get_text('words'):
                    x0, y0, x1, y1, messyText, *_ = word
                    if y1 < areaSEEGP_y0:
                        tidyText = messyText.replace('\n',' ').lower()
                        extractUOPwords.append(tidyText)

    return extractUOPwords

In [33]:
# iterate pages in the pdf and extract words, preferrably between the UOP and SEEGP sections or else from UOP to end

def wordsUOP(keep_areaSEEGP, document, areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0):
    # language = language

    pdf = pymupdf.open(document)

    if keep_areaSEEGP == True:
        extractUOPwords = wordsUOP_endPage(document, areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0)
        UOPwordsNoDupes = list(set(extractUOPwords))

    elif keep_areaSEEGP == False:
        extractUOPwords = []

# iterate pages
        for page_idx in range(len(pdf)):
            page = pdf[page_idx]
       
    # process two page scenarios and extract text as words

        # assume UOP across > 1 page
        # B: current page is start page
            if page_idx == areaUOP_page:
                for word in page.get_text('words'):
                    x0, y0, x1, y1, messyText, *_ = word
                    if y0 > areaUOP_y1:
                        tidyText = messyText.replace('\n',' ').lower()
                        extractUOPwords.append(tidyText)

        # E: current page is after the UOP start page
            elif page_idx > areaUOP_page:
                for word in page.get_text('words'):
                    x0, y0, x1, y1, messyText, *_ = word
                    tidyText = messyText.replace('\n',' ').lower()
                    extractUOPwords.append(tidyText)
    
        UOPwordsNoDupes = list(set(extractUOPwords))
    
    return UOPwordsNoDupes

In [34]:
# process words into category word dictionaries where token.similarity score passes threshold

def UOPwords_to_Catwords(language, UOPwordsNoDupes):

    sim_th_en = 0.65
    sim_th_pt = 0.65
    sim_th_es = 0.65

    if language == 'EN':
        nlp = nlp_en
        all = all_cat_words_en
        re = renewable_energy_en
        ee = energy_efficiency_en
        ppc = pollution_prevention_and_control_en
        esml = environmentally_sustainable_management_of_living_natural_resources_and_land_use_en
        tabc = terrestrial_and_aquatic_biodiversity_conservation_en
        ct = clean_transportation_en
        swwm = sustainable_water_and_wastewater_management_en
        cca = climate_change_adaptation_en
        ce = circular_economy_and_or_ecoefficient_projects_en
        gb = green_buildings_en
        similarity_threshold = sim_th_en
    elif language == 'PT':
        nlp = nlp_pt
        all = all_cat_words_pt
        re = renewable_energy_pt
        ee = energy_efficiency_pt
        ppc = pollution_prevention_and_control_pt
        esml = environmentally_sustainable_management_of_living_natural_resources_and_land_use_pt
        tabc = terrestrial_and_aquatic_biodiversity_conservation_pt
        ct = clean_transportation_pt
        swwm = sustainable_water_and_wastewater_management_pt
        cca = climate_change_adaptation_pt
        ce = circular_economy_and_or_ecoefficient_projects_pt
        gb = green_buildings_pt
        similarity_threshold = sim_th_pt
    elif language == 'ES':
        nlp = nlp_es
        all = all_cat_words_es
        re = renewable_energy_es
        ee = energy_efficiency_es
        ppc = pollution_prevention_and_control_es
        esml = environmentally_sustainable_management_of_living_natural_resources_and_land_use_es
        tabc = terrestrial_and_aquatic_biodiversity_conservation_es
        ct = clean_transportation_es
        swwm = sustainable_water_and_wastewater_management_es
        cca = climate_change_adaptation_es
        ce = circular_economy_and_or_ecoefficient_projects_es
        gb = green_buildings_es
        similarity_threshold = sim_th_es

    # outputs
    simsre = {}
    simsee = {}
    simsppc = {}
    simsesml = {}
    simstabc = {}
    simsct = {}
    simsswwm = {}
    simscca = {}
    simsce = {}
    simsgb = {}
    

    # renewable_energy
    for worda in re:
        doca = nlp(worda)
        for wordb in UOPwordsNoDupes:
            docb = nlp(wordb)
            if doca.similarity(docb) >= similarity_threshold:
                sim = doca.similarity(docb)
                simsre[doca[0].text + ' ' + docb[0].text] = sim

    # energy_efficiency
    for wordc in ee:
        docc = nlp(wordc)
        for wordb in UOPwordsNoDupes:
            docb = nlp(wordb)
            if docc.similarity(docb) >= similarity_threshold:
                sim = docc.similarity(docb)
                simsee[docc[0].text + ' ' + docb[0].text] = sim
    
    # pollution_prevention_and_control
    for wordd in ppc:
        docd = nlp(wordd)
        for wordb in UOPwordsNoDupes:
            docb = nlp(wordb)
            if docd.similarity(docb) >= similarity_threshold:
                sim = docd.similarity(docb)
                simsppc[docd[0].text + ' ' + docb[0].text] = sim

    # environmentally_sustainable_management_of_living_natural_resources_and_land_use
    for worde in esml:
        doce = nlp(worde)
        for wordb in UOPwordsNoDupes:
            docb = nlp(wordb)
            if doce.similarity(docb) >= similarity_threshold:
                sim = doce.similarity(docb)
                simsesml[doce[0].text + ' ' + docb[0].text] = sim

    # terrestrial_and_aquatic_biodiversity_conservation
    for wordf in tabc:
        docf = nlp(wordf)
        for wordb in UOPwordsNoDupes:
            docb = nlp(wordb)
            if docf.similarity(docb) >= similarity_threshold:
                sim = docf.similarity(docb)
                simstabc[docf[0].text + ' ' + docb[0].text] = sim

    # clean_transportation
    for wordg in ct:
        docg = nlp(wordg)
        for wordb in UOPwordsNoDupes:
            docb = nlp(wordb)
            if docg.similarity(docb) >= similarity_threshold:
                sim = docg.similarity(docb)
                simsct[docg[0].text + ' ' + docb[0].text] = sim

    # sustainable_water_and_wastewater_management
    for wordh in swwm:
        doch = nlp(wordh)
        for wordb in UOPwordsNoDupes:
            docb = nlp(wordb)
            if doch.similarity(docb) >= similarity_threshold:
                sim = doch.similarity(docb)
                simsswwm[doch[0].text + ' ' + docb[0].text] = sim

    # climate_change_adaptation
    for wordi in cca:
        doci = nlp(wordi)
        for wordb in UOPwordsNoDupes:
            docb = nlp(wordb)
            if doci.similarity(docb) >= similarity_threshold:
                sim = doci.similarity(docb)
                simscca[doci[0].text + ' ' + docb[0].text] = sim

        # circular_economy_and_or_ecoefficient_projects
    for wordj in ce:
        docj = nlp(wordj)
        for wordb in UOPwordsNoDupes:
            docb = nlp(wordb)
            if docj.similarity(docb) >= similarity_threshold:
                sim = docj.similarity(docb)
                simsce[docj[0].text + ' ' + docb[0].text] = sim

    # green_buildings
    for wordk in gb:
        dock = nlp(wordk)
        for wordb in UOPwordsNoDupes:
            docb = nlp(wordb)
            if dock.similarity(docb) >= similarity_threshold:
                sim = dock.similarity(docb)
                simsgb[dock[0].text + ' ' + docb[0].text] = sim

    return simsre, simsee, simsppc, simsesml, simstabc, simsct, simsswwm, simscca, simsce, simsgb

In [52]:
# list of pdf filenames
pdf_en = ['Green_social_bond_framework_series_ad_ae_2019', 'ISA_CTM_FRAMEWORK', 'SONDA_S_A__GREEN_BOND_FRAMEWORK',
          'CIFI_Green_Bond_Framework', 'BTG_Sustainable_Financing_Framework', 'CABEI_Green_Bond_Framework', 
          'Genneia_Green_Bond_Framework', 'FS_Green_Bond_Framework_-_July_2021', 'CAFs_GREEN_BOND_FRAMEWORK', 
          'BTG_Pactual_Green,_Social_and_Sustainable_Financing_Framework', 'ILAP_Green_Financing_Framework', 
          'EGE_Haina_Green_Securities_Framework', 'CADU_GREEN_BOND_FRAMEWORK', 'Bci_Sustainable_Financing_Framework',
          'FS_Green_Bond_Framework_-_November_2020', 'Sicredi_Green_Bond_Framework', 'Nacional_Financiera_Green_Bond_USD',
          'Green_Bond_Financing_Framework', 'Green_Bond_Framework_of_Banco_Guayaquil', 
          'Marco_de_referencia_de_Bonos_Verdes_Soberanos_de_Colombia', 'Green_Finance_Framework_Interchile']
pdf_en_lines = ['Chile_Sustainable_Bond_Framework', 'Genneia_Green_Financing_Framework']
pdf_es = ['Cartilla_Bonos_Verdes', 'Bono_Azul_-_Framework', 'Marco_de_referencia_de_bono_verde_Coopeguanacaste,_R_L_',  
          'Marco_de_Referencia_del_Bono_Verde_de_la_Ciudad_de_Mexico', 'Nacional_Financiera_Green_Bond_MXN',
          'Marco_de_Gestión_de_Bono_Verde', 'Bono_Verde_de_Bancoldex_Framework']
pdf_es_lines = ['Marco_de_Uso_de_Fondo_para_la_Emision_de_Bonos_Verdes,_Sociales_o_Sostenibles_BDP_I']
pdf_pt = ['Green_Bond_Framework', 'Green_Bonds_Framework_Athon_2020']

In [35]:
# run the pdf through the pipeline - first pdf, initialise the dataframes

document = '/Users/elisabethwatson/Birkbeck/PGC ADS/Module 3 Project/Datasets/GBTP 260201/inscope framework reports/Climate_Bond_Framework_of_E1_SUBHOLDING_S_A__in_2021.pdf'
language = 'EN'
tableStrategy = 'lines_strict'

filename, tableCount, tablePages, tableHeaders, tableDFs = catTable(document, tableStrategy)
uniqueCatsNoDupes, table_idx, CatwordsFFinal, dfsimScores = tableAssess(language, tableCount, tablePages, tableHeaders, tableDFs)
results_UOP, results_SEEGP = fontInfo(language, document)
max_idx_UOP, max_idx_SEEGP = find_max_font(results_UOP, results_SEEGP)
areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0 = tocCheck(results_UOP, results_SEEGP, max_idx_UOP, max_idx_SEEGP)
keep_areaSEEGP = keepSEEGP(areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0)
UOPwordsNoDupes = wordsUOP(keep_areaSEEGP, document, areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0)

# dataframe output for transparency on how pipeline has processed the pdf
columns = ['filename', 'language', 'tableCount', 'areaUOP_page', 'areaUOP_y1', 'areaSEEGP_page', 'areaSEEGP_y0', 'keep_areaSEEGP', 'countUOP_words']
results_df = pd.DataFrame(columns=columns)
results_df.loc[len(results_df)] = [filename, language, tableCount, areaUOP_page, areaUOP_y1, areaSEEGP_page,areaSEEGP_y0, keep_areaSEEGP, len(UOPwordsNoDupes)]

# table info
columns = ['filename', 'tablePages_list', 'table.Headers_list', 'countCat_words', 'unique compliant Categories_list', 'table_idx_list', 'unique Cats all', 'simScores for cleanup']
table_df = pd.DataFrame(columns=columns)

# UOP start and end info
columns = ['filename', 'results_UOP_list (text, fontSize, bbox, page_idx)', 'max_idx_UOP', 'results_SEEGP_list (text, fontSize, bbox, page_idx)', 'max_idx_SEEGP']
UOP_df = pd.DataFrame(columns=columns)
UOP_df.loc[len(UOP_df)] = [filename, results_UOP, max_idx_UOP, results_SEEGP, max_idx_SEEGP]

# final Cateogory info
if len(uniqueCatsNoDupes) == 0:
    simsre, simsee, simsppc, simsesml, simstabc, simsct, simsswwm, simscca, simsce, simsgb = UOPwords_to_Catwords(language, UOPwordsNoDupes)
    print('')
    print('categories from UOP portion')
    columns = ['filename', 'renewable_energy (dict.keys obj)', 're_scores (dict.values obj)', 'energy_efficiency', 'ee_scores', 'pollution_prevention_and_control', 'ppc_scores', 
               'environmentally_sustainable_management_of_living_natural_resources_and_land_use', 'esml_scores',
               'terrestrial_and_aquatic_biodiversity_conservation', 'tabc_scores', 'clean_transportation', 'ct_scores',
               'sustainable_water_and_wastewater_management', 'swwm_scores', 'climate_change_adaptation', 'cca_scores' ,
               'circular_economy_and_or_ecoefficient_projects', 'ce_scores', 'green_buildings', 'gb_scores']
    UOP_Words_df = pd.DataFrame(columns=columns)
    UOP_Words_df.loc[len(UOP_Words_df)] = [filename, simsre.keys(), simsre.values(), simsee.keys(), simsee.values(), 
                                           simsppc.keys(), simsppc.values(), simsesml.keys(), simsesml.values(),
                                           simstabc.keys(), simstabc.values(), simsct.keys(), simsct.values(), 
                                           simsswwm.keys(), simsswwm.values(), simscca.keys(), simscca.values(),
                                           simsce.keys(), simsce.values(), simsgb.keys(), simsgb.values()]
else:
    print('')
    print('categories from tables')
    table_df.loc[len(table_df)] = [filename, tablePages, tableHeaders, len(CatwordsFFinal), CatwordsFFinal, table_idx, uniqueCatsNoDupes, dfsimScores]

/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_76729/1802488584.py:70: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  if doca.similarity(docb) >= similarity_threshold:
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_76729/1802488584.py:79: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  if docc.similarity(docb) >= similarity_threshold:
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_76729/1802488584.py:88: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  if docd.similarity(docb) >= similarity_threshold:
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_76729/1802488584.py:97: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  if doce.similarity(docb) >= similarity_threshold:
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_76729/1802488584.py:106: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  if docf.similarity(docb) >= similarity_threshold:
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_76729/1802488584.py:115: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  if docg.similarity(docb) >= similarity_threshold:
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_76729/1802488584.py:124: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  if doch.similarity(docb) >= similarity_threshold:
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_76729/1802488584.py:133: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  if doci.similarity(docb) >= similarity_threshold:
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_76729/1802488584.py:142: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  if docj.similarity(docb) >= similarity_threshold:
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_76729/1802488584.py:151: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  if dock.similarity(docb) >= similarity_threshold:

categories from UOP portion

In [59]:
# run the pdf through the pipeline - subsequent pdfs, populate the dataframes



filepath = '/Users/elisabethwatson/Birkbeck/PGC ADS/Module 3 Project/Datasets/GBTP 260201/refinement_reports/'
extention = '.pdf'
language = 'PT'
tableStrategy = 'lines_strict'

for pdf in pdf_pt:
    document = filepath + pdf + extention

    filename, tableCount, tablePages, tableHeaders, tableDFs = catTable(document, tableStrategy)
    uniqueCatsNoDupes, table_idx, CatwordsFFinal, dfsimScores = tableAssess(language, tableCount, tablePages, tableHeaders, tableDFs)
    results_UOP, results_SEEGP = fontInfo(language, document)
    max_idx_UOP, max_idx_SEEGP = find_max_font(results_UOP, results_SEEGP)
    areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0 = tocCheck(results_UOP, results_SEEGP, max_idx_UOP, max_idx_SEEGP)
    keep_areaSEEGP = keepSEEGP(areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0)
    UOPwordsNoDupes = wordsUOP(keep_areaSEEGP, document, areaUOP_page, areaUOP_y1, areaSEEGP_page, areaSEEGP_y0)

    results_df.loc[len(results_df)] = [filename, language, tableCount, areaUOP_page, areaUOP_y1, areaSEEGP_page,areaSEEGP_y0, keep_areaSEEGP, len(UOPwordsNoDupes)]

    UOP_df.loc[len(UOP_df)] = [filename, results_UOP, max_idx_UOP, results_SEEGP, max_idx_SEEGP]

    if len(uniqueCatsNoDupes) == 0:
        simsre, simsee, simsppc, simsesml, simstabc, simsct, simsswwm, simscca, simsce, simsgb = UOPwords_to_Catwords(language, UOPwordsNoDupes)
        print('')
        print('categories from UOP portion')
        UOP_Words_df.loc[len(UOP_Words_df)] = [filename, simsre.keys(), simsre.values(), simsee.keys(), simsee.values(), 
                                           simsppc.keys(), simsppc.values(), simsesml.keys(), simsesml.values(),
                                           simstabc.keys(), simstabc.values(), simsct.keys(), simsct.values(), 
                                           simsswwm.keys(), simsswwm.values(), simscca.keys(), simscca.values(),
                                           simsce.keys(), simsce.values(), simsgb.keys(), simsgb.values()]
    else:
        print('')
        print('categories from tables')
        table_df.loc[len(table_df)] = [filename, tablePages, tableHeaders, len(CatwordsFFinal), CatwordsFFinal, table_idx, uniqueCatsNoDupes, dfsimScores]

/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_76729/3630868540.py:77: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  if docCat.similarity(docx) >= cleanup_TH:

categories from tables

/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_76729/1802488584.py:70: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  if doca.similarity(docb) >= similarity_threshold:
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_76729/1802488584.py:79: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  if docc.similarity(docb) >= similarity_threshold:
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_76729/1802488584.py:88: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  if docd.similarity(docb) >= similarity_threshold:
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_76729/1802488584.py:97: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  if doce.similarity(docb) >= similarity_threshold:
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_76729/1802488584.py:106: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  if docf.similarity(docb) >= similarity_threshold:
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_76729/1802488584.py:115: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  if docg.similarity(docb) >= similarity_threshold:
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_76729/1802488584.py:124: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  if doch.similarity(docb) >= similarity_threshold:
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_76729/1802488584.py:133: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  if doci.similarity(docb) >= similarity_threshold:
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_76729/1802488584.py:142: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  if docj.similarity(docb) >= similarity_threshold:
/var/folders/pf/t466z2553r9f82s2v7n0pgfr0000gn/T/ipykernel_76729/1802488584.py:151: UserWarning: [W008] Evaluating Doc.similarity based on empty vectors.
  if dock.similarity(docb) >= similarity_threshold:

categories from UOP portion

In [60]:
results_df

,filename,language,tableCount,areaUOP_page,areaUOP_y1,areaSEEGP_page,areaSEEGP_y0,keep_areaSEEGP,countUOP_words
0,Climate_Bond_Framework_of_E1_SUBHOLDING_S_A__i...,EN,1,1,420.328369,2,354.484863,True,188
1,Green_social_bond_framework_series_ad_ae_2019.pdf,EN,3,1,98.540031,1,87.500031,False,927
2,ISA_CTM_FRAMEWORK.pdf,EN,11,8,271.757019,3,201.050018,False,503
3,SONDA_S_A__GREEN_BOND_FRAMEWORK.pdf,EN,0,4,124.099983,4,435.190002,True,124
4,CIFI_Green_Bond_Framework.pdf,EN,0,7,569.777405,8,169.974762,True,66
5,BTG_Sustainable_Financing_Framework.pdf,EN,1,20,80.458229,31,60.549740,True,1311
6,CABEI_Green_Bond_Framework.pdf,EN,5,7,441.189972,11,81.259979,True,387
7,Genneia_Green_Bond_Framework.pdf,EN,0,8,110.361000,9,104.296997,True,169
8,FS_Green_Bond_Framework_-_July_2021.pdf,EN,0,11,455.748077,5,223.619537,False,679
9,CAFs_GREEN_BOND_FRAMEWORK.pdf,EN,6,7,262.438385,9,336.903778,True,271
10,"BTG_Pactual_Green,_Social_and_Sustainable_Fina...",EN,4,14,406.338043,18,499.063019,True,327
11,ILAP_Green_Financing_Framework.pdf,EN,0,0,481.347198,0,470.681610,False,910
12,EGE_Haina_Green_Securities_Framework.pdf,EN,1,10,492.464996,12,428.401001,True,275
13,CADU_GREEN_BOND_FRAMEWORK.pdf,EN,0,6,140.128403,0,758.464783,False,578
14,Bci_Sustainable_Financing_Framework.pdf,EN,0,7,110.545990,1,28.432018,False,909
15,FS_Green_Bond_Framework_-_November_2020.pdf,EN,0,7,546.994019,7,403.429993,False,653
16,Sicredi_Green_Bond_Framework.pdf,EN,2,3,402.529999,4,579.070007,True,236
17,Nacional_Financiera_Green_Bond_USD.pdf,EN,1,3,123.770012,3,356.360016,True,84
18,Green_Bond_Financing_Framework.pdf,EN,3,7,179.089981,8,559.180054,True,186
19,Green_Bond_Framework_of_Banco_Guayaquil.pdf,EN,16,6,109.511734,11,71.712212,True,622
20,Marco_de_referencia_de_Bonos_Verdes_Soberanos_...,EN,1,14,479.131409,19,351.234100,True,731
21,Green_Finance_Framework_Interchile.pdf,EN,1,7,321.529999,9,111.740021,True,210
22,Chile_Sustainable_Bond_Framework.pdf,EN,13,18,217.077713,3,216.104080,False,1443
23,Genneia_Green_Financing_Framework.pdf,EN,2,1,600.482239,0,0.000000,False,1267
24,Cartilla_Bonos_Verdes.pdf,ES,0,10,433.616699,16,464.230499,True,497
25,Bono_Azul_-_Framework.pdf,ES,5,1,336.792603,1,390.216888,True,15
26,Marco_de_referencia_de_bono_verde_Coopeguanaca...,ES,18,15,89.151588,16,541.706238,True,271
27,Marco_de_Referencia_del_Bono_Verde_de_la_Ciuda...,ES,0,0,490.869995,0,395.050018,False,818
28,Nacional_Financiera_Green_Bond_MXN.pdf,ES,6,3,188.569992,3,534.459961,True,99
29,Marco_de_Gestión_de_Bono_Verde.pdf,ES,3,7,411.209991,2,210.830017,False,400
30,Bono_Verde_de_Bancoldex_Framework.pdf,ES,1,1,492.789978,3,365.630005,True,325
31,Marco_de_Uso_de_Fondo_para_la_Emision_de_Bonos...,ES,43,5,102.917595,32,535.163818,True,2949
32,Green_Bond_Framework.pdf,PT,5,1,304.611969,15,133.837967,True,1602
33,Green_Bonds_Framework_Athon_2020.pdf,PT,2,4,428.291565,6,551.981140,True,379

In [61]:
table_df

,filename,tablePages_list,table.Headers_list,countCat_words,unique compliant Categories_list,table_idx_list,unique Cats all,simScores for cleanup
0,Green_social_bond_framework_series_ad_ae_2019.pdf,"[3, 6, 7]","[[Category, Project name, Goal], [Categories o...",2,"[sanitation, potable water supply]","[0, 0, 0, 1, 1, 1]","[sanitation, resilient infrastructure, potable...",0 sanitat...
1,ISA_CTM_FRAMEWORK.pdf,"[4, 5, 7, 8, 9, 15, 16, 17, 18]","[[Eligible Project Category, Questions, Alignm...",2,"[energy efficiency, renewable energy]","[0, 0]","[energy efficiency, renewable energy]",0 energy ...
2,CABEI_Green_Bond_Framework.pdf,"[7, 8, 9, 10, 12]","[[Eligible\nGreen\nProjects\nCategories, Sub-c...",3,"[sustainable land use, water management, renew...","[0, 4, 4, 4, 4]","[clean transport, water management, sustainabl...",0 water man...
3,CAFs_GREEN_BOND_FRAMEWORK.pdf,"[1, 2, 8, 9]","[[Measure of Units, Col1], [Graphics, Content]...",4,[sustainable management of living natural reso...,"[2, 2, 2, 2]",[sustainable management of living natural reso...,...
4,"BTG_Pactual_Green,_Social_and_Sustainable_Fina...","[15, 16, 17, 19]","[[Green\nProject\nCategory, Use of\nProceeds, ...",6,"[afof rdable housing, sustainable water and wa...","[0, 1, 1, 1, 1, 2, 2, 3, 3, 3, 3, 3, 3, 3]","[afof rdable housing, afof rdable basic infras...",...
5,Sicredi_Green_Bond_Framework.pdf,"[4, 6]","[[Eligible\nCategories, Description, Objective...",2,"[energy efficiency, renewable energy]","[0, 0]","[energy efficiency, renewable energy]",0 energy ...
6,Green_Bond_Financing_Framework.pdf,"[7, 8, 10]",[[Eligible Category aligned\nwith ICMA Green B...,2,"[energy efficiency, clean transportation]","[0, 2, 2]","[energy efficiency, clean transportation]",0 ...
7,Green_Bond_Framework_of_Banco_Guayaquil.pdf,"[6, 7, 8, 9, 10, 18, 19, 29, 30, 31, 38, 39]","[[GBP Eligible\nGreen Assets\nCategory, Banco ...",2,"[energy efficiency, renewable energy]","[0, 1, 1, 1, 1]","[energy efficiency, renewable energy]",0 energy ...
8,Green_Finance_Framework_Interchile.pdf,[8],"[[Eligible Project Category, Questions, Alignm...",3,"[climate change adaptation, energy efficiency,...","[0, 0, 0]","[renewable energy, energy efficiency, climate ...",0...
9,Chile_Sustainable_Bond_Framework.pdf,"[0, 19, 20, 21, 22, 23, 24, 25, 26, 30, 37, 38...","[[Col0, Ministry of\nFinance\nGovernment of Ch...",8,"[access to basic housing, food security, acces...","[5, 5, 5, 5, 6, 6, 7, 7, 7, 8, 8, 10, 10, 10, ...","[natural resources, use of land and protected ...",...
10,Genneia_Green_Financing_Framework.pdf,"[5, 7]","[[Col0, 20161, 20202, 20251, 20301], [Eligible...",1,[renewable energy],[1],[renewable energy],0 renewable...
11,Nacional_Financiera_Green_Bond_MXN.pdf,"[3, 9, 10, 11, 17]","[[Categoría, Actividades elegibles], [Col0, Pr...",2,"[centrales eólicas (solo terrestres), pequeñas...","[0, 0]","[pequeñas centrales hidroeléctricas, centrales...",...
12,Marco_de_Gestión_de_Bono_Verde.pdf,"[5, 8, 9]","[[Norma de\nDesempeño, Estatus1, Descripción],...",1,[proyecto de energías renovables (energía hidr...,[1],[proyecto de energías renovables (energía hidr...,...
13,Marco_de_Uso_de_Fondo_para_la_Emision_de_Bonos...,"[3, 4, 8, 16, 18, 19, 20, 21, 22, 23, 24, 25, ...",[[Contribuciones Nacionales Determinadas (NDCs...,1,[energías renovables],"[34, 34, 34, 34, 35, 35]","[eficiencia energética49 50, verdes, energías ...",...
14,Green_Bond_Framework.pdf,"[10, 14, 19, 21, 22]","[[Categoria, Descrição], [Projeto, Capaci\nda ...",2,"[energia renovável, transmissão de energia]","[0, 0]","[energia renovável, transmissão de energia]",...

In [62]:
UOP_df

,filename,"results_UOP_list (text, fontSize, bbox, page_idx)",max_idx_UOP,"results_SEEGP_list (text, fontSize, bbox, page_idx)",max_idx_SEEGP
0,Climate_Bond_Framework_of_E1_SUBHOLDING_S_A__i...,"[(Use of Proceeds , 11.039999961853027, (85.1...",0,[(Selection and Evaluation of Eligible Green P...,0
1,Green_social_bond_framework_series_ad_ae_2019.pdf,"[(SBPs: Use of Funds, Evaluation and Selection...",0,"[(SBPs: Use of Funds, Evaluation and Selection...",0
2,ISA_CTM_FRAMEWORK.pdf,"[(Use of the proceeds , 11.039999961853027, (1...",4,"[(Process for Evaluation and Selection , 11.03...",0
3,SONDA_S_A__GREEN_BOND_FRAMEWORK.pdf,[(3.1 Use of Proceeds ...........................,1,[(3.2 Project Selection and Assessment Process...,1
4,CIFI_Green_Bond_Framework.pdf,"[(a. Use of Proceeds, 12.531599998474121, (69....",0,"[(b. Project Selection Criteria , 12.531599998...",0
5,BTG_Sustainable_Financing_Framework.pdf,"[(Use of Proceeds, 13.0, (241.72439575195312, ...",2,[(Process for Project Selection and Evaluation...,4
6,CABEI_Green_Bond_Framework.pdf,[(Use of Proceeds ...............................,1,[(Process for Project Evaluation and Selection...,3
7,Genneia_Green_Bond_Framework.pdf,"[( Use of Proceeds, 13.0, (253.3719940185547,...",1,"[(Process for Project Evaluation , 13.0, (269...",2
8,FS_Green_Bond_Framework_-_July_2021.pdf,"[(Use of Proceeds , 12.000450134277344, (110.6...",0,"[(theme within the company. Furthermore, in th...",0
9,CAFs_GREEN_BOND_FRAMEWORK.pdf,[(1. Use of Proceeds ............................,2,[(2. Process for Project Evaluation and Select...,6
10,"BTG_Pactual_Green,_Social_and_Sustainable_Fina...","[(Use of Proceeds , 12.0, (184.590087890625, 6...",3,"[(Process for Project , 12.0, (184.59008789062...",5
11,ILAP_Green_Financing_Framework.pdf,"[(1. Use of proceeds , 8.800000190734863, (77....",0,[( 2. Process for project evaluation and selec...,0
12,EGE_Haina_Green_Securities_Framework.pdf,"[(• Use of Proceeds\t, 10.0, (259.912902832031...",5,[(• Project Selection and Evaluation Process\t...,1
13,CADU_GREEN_BOND_FRAMEWORK.pdf,"[(Use of Proceeds , 11.039999961853027, (84.98...",0,"[(selection processes; and, the reporting meth...",0
14,Bci_Sustainable_Financing_Framework.pdf,"[(Green Use of Proceeds instruments: , 9.0, (6...",10,"[(Process for , 9.0, (277.7300109863281, 28.43...",0
15,FS_Green_Bond_Framework_-_November_2020.pdf,"[(Use of Proceeds , 12.0, (110.66000366210938,...",0,[(Capital Markets Association are voluntary pr...,0
16,Sicredi_Green_Bond_Framework.pdf,[(2.1 Use of Proceeds ...........................,2,[(2.2 Project evaluation & selection ............,3
17,Nacional_Financiera_Green_Bond_USD.pdf,"[(3.1 Use of Proceeds , 11.039999961853027, (9...",2,"[(3.2 Project Selection Process , 11.039999961...",1
18,Green_Bond_Financing_Framework.pdf,"[(Use of Proceeds , 11.039999961853027, (108.0...",1,[(5.2 Process of Project Evaluation and S...,5
19,Green_Bond_Framework_of_Banco_Guayaquil.pdf,[(First Principle – Use of Proceeds .............,3,[(Second Principle – Process for Project Evalu...,6
20,Marco_de_referencia_de_Bonos_Verdes_Soberanos_...,"[(Use of proceeds , 11.0, (360.3396911621094, ...",3,"[(Process for Project Evaluation and , 11.0, (...",5
21,Green_Finance_Framework_Interchile.pdf,[(4.1 Use of Proceeds ...........................,2,[(4.2 Process for Project Evaluation and Selec...,5
22,Chile_Sustainable_Bond_Framework.pdf,"[(Use of Proceeds, 8.0, (311.42449951171875, 5...",2,"[(Project Evaluation , 11.0, (123.502014160156...",0
23,Genneia_Green_Financing_Framework.pdf,"[(Use of proceeds, 9.0, (73.48359680175781, 58...",0,[],0
24,Cartilla_Bonos_Verdes.pdf,"[(Uso de Fondos Proyectos Verdes Elegibles , 1...",3,"[(Procedimiento Selección y Evaluación , 12.0,...",2
25,Bono_Azul_-_Framework.pdf,"[(2.1 Uso de los recursos , 12.0, (41.13280105...",0,[(2.2 Proceso de evaluación y selección de pr...,0
26,Marco_de_referencia_de_bono_verde_Coopeguanaca...,[(Destinos de Fondos. ...........................,1,[(Proceso de evaluación y selección de proyect...,2
27,Marco_de_Referencia_del_Bono_Verde_de_la_Ciuda...,"[(1. Uso de los Recursos , 12.0, (49.680000305...",0,[(2. Proceso de Evaluación y Selección de proy...,0
28,Nacional_Financiera_Green_Bond_MXN.pdf,"[(3.1. Uso de los Fondos , 11.039999961853027,...",1,[(3.2. Proceso de Evaluación y Selección de Pr...,2
29,Marco_de_Gestión_de_Bono_Verde.pdf,[(Uso de los Fondos .............................,2,[(Proceso de Selección y Evaluación de Proyect...,1
30,Bono_Verde_de_Bancoldex_Framework.pdf,"[(Uso de los recursos , 12.0, (113.41999816894...",0,[(ingresos o recursos; (ii) proceso de evaluac...,2
31,Marco_de_Uso_de_Fondo_para_la_Emision_de_Bonos...,[(Marco de uso de fondos para las emisiones de...,7,[(3.2. Selección y Evaluación de Proyectos ......,2
32,Green_Bond_Framework.pdf,"[(Usos dos Recursos , 12.0, (115.25, 291.32797...",0,"[(Avaliação e Seleção de Ativos , 12.0, (103.2...",0
33,Green_Bonds_Framework_Athon_2020.pdf,[(Uso de Recursos ...............................,2,[(Processo de Avaliação e Seleção de Projetos ...,1

In [63]:
UOP_Words_df

,filename,renewable_energy (dict.keys obj),re_scores (dict.values obj),energy_efficiency,ee_scores,pollution_prevention_and_control,ppc_scores,environmentally_sustainable_management_of_living_natural_resources_and_land_use,esml_scores,terrestrial_and_aquatic_biodiversity_conservation,...,clean_transportation,ct_scores,sustainable_water_and_wastewater_management,swwm_scores,climate_change_adaptation,cca_scores,circular_economy_and_or_ecoefficient_projects,ce_scores,green_buildings,gb_scores
0,Climate_Bond_Framework_of_E1_SUBHOLDING_S_A__i...,"(renewable electricity, renewable renewable, r...","(0.6735955476760864, 1.0, 0.6823998093605042, ...",(),(),(pollution emissions),(0.6611024141311646),(),(),(),...,(electric electricity),(0.671796441078186),(),(),(),(),(),(),(),()
1,SONDA_S_A__GREEN_BOND_FRAMEWORK.pdf,"(renewable biomass, renewable renewable, renew...","(0.6758356690406799, 1.0, 0.6823998093605042, ...","(efficiency efficient, efficiency efficiency)","(0.7573143839836121, 1.0)","(pollution emissions, waste waste)","(0.7256803512573242, 1.0)",(),(),(),...,(),(),(),(),(),(),(),(),"(buildings buildings, buildings building)","(1.0, 0.797235906124115)"
2,CIFI_Green_Bond_Framework.pdf,"(renewable renewable, renewable energy, renewa...","(1.0, 0.6823998093605042, 0.6758356690406799, ...",(),(),"(waste waste, waste recycling)","(1.0, 0.7248635292053223)",(),(),(),...,(),(),"(wastewater wastewater, treatment treatment)","(1.0, 1.0)",(),(),"(recycle recycling, reuse recycling)","(0.8278464674949646, 0.6530712246894836)",(),()
3,BTG_Sustainable_Financing_Framework.pdf,"(renewable sustainable, renewable non, renewab...","(0.6980571150779724, 0.72650146484375, 0.67585...","(efficiency efficient, efficiency efficiency)","(0.7573143839836121, 1.0)","(pollution pollution, pollution emissions, pol...","(1.0, 0.6577414870262146, 0.7345117926597595, ...","(land “, land land, agriculture agricultural, ...","(0.8367156982421875, 1.0, 0.898859441280365, 0...","(terrestrial terrestrial, biodiversity ecosyst...",...,"(transportation transport, transportation tran...","(0.6649630665779114, 1.0, 0.6578854918479919, ...","(water water, wastewater wastewater, sanitatio...","(1.0, 1.0, 1.0, 0.8470622897148132)","(adaptation adaptation, disaster disasters)","(1.0, 0.8176723718643188)","(recycle recyclable, recycle recycling, reuse ...","(0.6732295155525208, 0.8278464674949646, 0.653...","(buildings buildings, housing housing)","(0.8454830050468445, 0.8488945960998535)"
4,Genneia_Green_Bond_Framework.pdf,"(renewable renewable, renewable energy, solar ...","(1.0, 0.6823998093605042, 1.0, 1.0, 0.65110641...",(),(),(pollution emissions),(0.7256803512573242),(),(),(),...,"(battery battery, charger battery)","(1.0, 0.8197756409645081)",(),(),(),(),(),(),(),()
5,FS_Green_Bond_Framework_-_July_2021.pdf,"(renewable sustainable, renewable biofuel, ren...","(0.6980571150779724, 0.6902978420257568, 0.675...","(efficiency productivity, efficiency efficient)","(0.6503185033798218, 0.7573143839836121)","(pollution environmental, pollution impacts)","(0.7345117926597595, 0.6625850796699524)","(land lands, land land, agriculture agricultur...","(0.8242226839065552, 1.0, 1.0, 0.7442550659179...","(biodiversity deforestation, conservation envi...",...,"(electric electricity, car car, vehicle car, n...","(0.671796441078186, 1.0, 0.7667538523674011, 0...",(water water),(1.0),(),(),(),(),(),()
6,ILAP_Green_Financing_Framework.pdf,"(renewable sustainable, renewable renewable, r...","(0.6980571150779724, 1.0, 0.6823998093605042, ...",(),(),"(pollution environmental, pollution pollution,...","(0.7345117926597595, 1.0, 0.7256803512573242)",(),(),"(biodiversity biodiversity, conservation envir...",...,(electric electricity),(0.671796441078186),(),(),(adaptation adaptation),(0.8294525742530823),(),(),(),()
7,EGE_Haina_Green_Securities_Framework.pdf,"(renewable renewable, renewable energy, solar ...","(1.0, 0.6823998093605042, 0.7906877398490906, ...",(),(),(),(),(land land),(1.0),(),...,(electric electric),(1.0),(water water),(1.0),(),(),(),(),(),()
8,CADU_GREEN_BOND_FRAMEWORK.pdf,"(renewable sustainable, renewable energy, rene...","(0.6980571150779724, 0.6823998093605042, 0.673...",(efficiency efficiency),(1.0),"(pollution environmental, pollution emissions,...","(0.7345117926597595, 0.7256803512573242, 0.662...",(),(),(conservation environmental),...,(electric electricity),(0.671796441078186),"(water water, wastewater sewage)","(1.0, 0.6909952759742737)",(),(),(),(),"(buildings buildings, buildings houses, housin...","(0.7504333257675171, 0.7476946711540222, 1.0)"
9,Bci_Sustainable_Financing_Framework.pdf,"(renewable sustainable, renewable fuels, renew...","(0.6980571150779724, 0.6609903573989868, 1.0, ...","(efficiency efficient, efficiency efficiency)","(0.7573143839836121, 1.0)","(pollution environmental, pollution emissions,...","(0.7345117926597595, 0.7256803512573242, 1.0, ...",(),(),(conservation environmental),...,"(transportation transport, transportation tran...","(0.7263567447662354, 1.0, 0.7536609768867493, ...","(water water, potable potable, wastewater sewe...","(0.8751156330108643, 1.0, 0.693297266960144, 1...",(),(),(),(),(buildings buildings),(1.0)
10,FS_Green_Bond_Framework_-_November_2020.pdf,"(renewable sustainable, renewable biofuel, ren...","(0.6980571150779724, 0.6902978420257568, 0.675...","(efficiency productivity, efficiency efficient)","(0.6503185033798218, 0.7573143839836121)","(pollution environmental, pollution impacts)","(0.7345117926597595, 0.6625850796699524)","(land lands, land land, agriculture agricultur...","(0.8242226839065552, 1.0, 1.0, 0.8988594412803...","(biodiversity deforestation, conservation envi...",...,"(electric electricity, car car, vehicle car, n...","(0.671796441078186, 1.0, 0.7667538523674011, 0...",(water water),(1.0),(),(),(),(),(),()
11,Nacional_Financiera_Green_Bond_USD.pdf,"(renewable energy, wind wind, power energy, tr...","(0.6823998093605042, 1.0, 0.6578531265258789, ...",(),(),(),(),(),(),(),...,(),(),(),(),(),(),(),(),(),()
12,Marco_de_referencia_de_Bonos_Verdes_Soberanos_...,"(renewable sustainable, renewable fuels, renew...","(0.6980571150779724, 0.6609903573989868, 1.0, ...",(efficiency efficiency),(0.8334598541259766),"(pollution environmental, pollution pollution,...","(0.7345117926597595, 1.0, 0.6625850796699524, ...","(land (, land land, agriculture agriculture, a...","(0.6583104133605957, 0.8250224590301514, 1.0, ...","(biodiversity ecosystems, biodiversity defores...",...,"(transportation transport, transportation frei...","(0.7263567447662354, 0.6578854918479919, 1.0, ...","(water water, wastewater wastewater, sanitatio...","(1.0, 1.0, 0.8295572996139526, 1.0)","(adaptation adaptation, disaster disaster, dis...","(1.0, 1.0, 0.7475464344024658)","(circular circular, recycle reuse, reuse reuse)","(1.0, 0.7356382608413696, 1.0)","(buildings buildings, buildings building, hous...","(0.8554772734642029, 0.797235906124115, 0.8488..."
13,Cartilla_Bonos_Verdes.pdf,"(renovable renovable, renovable sostenible, re...","(0.69474858045578, 0.6984525918960571, 0.66151...","(red red, acondicionar mantenimiento, acondici...","(0.7134368419647217, 0.6677801609039307, 0.664...","(contaminación implementación, contaminación t...","(0.7019962668418884, 0.6985132098197937, 0.746...","(. materiales, . energético, . saneamiento, . ...","(0.8391605615615845, 0.8899020552635193, 0.866...","(terrestre terrestres, biodiversidad sostenibi...",...,"(transporte mantenimiento, transporte almacena...","(0.710953414440155, 0.7192397713661194, 0.6518...","(de agua, de de, abastecimiento, potable, ...","(0.6834083199501038, 0.7838726043701172, 0.768...","(adecuación implementación, adecuación transic...","(0.8621118664741516, 0.7431526780128479, 0.783...","(reciclar reciclaje, reciclar reciclado, reuti...","(0.799636960029602, 0.7682274580001831, 0.6537...","(construcciones plantas, construcciones estaci...","(0.6657102108001709, 0.7819879055023193, 0.807..."
14,Bono_Azul_-_Framework.pdf,(),(),(),(),(de de),(0.9079835414886475),(),(),(conservación elegibilidad),...,(),(),(de de),(0.7838726043701172),(adecuación elegibilidad),(0.7566782236099243),(),(),(y y),(0.9070735573768616)
15,Marco_de_referencia_de_bono_verde_Coopeguanaca...,"(renovable renovables, solar solar, hidroelect...","(0.7942190170288086, 1.0, 0.6773465871810913, ...","(red red, acondicionar realizar)","(0.7134368419647217, 0.6741795539855957)","(contaminación descarbonización, contaminación...","(0.8036044239997864, 0.6967695951461792, 0.675...","(. huacas, . valorizables, . fondos, . r.l, . ...","(0.8966912627220154, 0.9034574627876282, 0.764...","(biodiversidad descarbonización, biodiversidad...",...,"(transporte servicio, eléctricos eléctricos, e...","(0.6618167757987976, 1.0, 0.7007869482040405, ...","(de de, saneamiento descarbonización, saneamie...","(0.7838726043701172, 0.7022638320922852, 0.680...","(adecuación descarbonización, adecuación movil...","(0.7524663805961609, 0.7253300547599792, 0.664...",(),(),"(construcciones municipalidades, construccione...","(0.7141571044921875, 0.6867573857307434, 0.786..."
16,Marco_de_Referencia_del_Bono_Verde_de_la_Ciuda...,"(renovable sustentable, renovable energético, ...","(0.6834493279457092, 0.6615170836448669, 0.794...","(red red, acondicionar mantenimiento, acondici...","(0.7134368419647217, 0.6677801609039307, 0.674...","(contaminación transición, contaminación inefi...","(0.6985132098197937, 0.7533332705497742, 0.660...","(. ríos, . fósiles, . méxico, . todavía, . per...","(0.683211088180542, 0.8289037346839905, 0.8943...","(biodiversidad sustentable, biodiversidad ambi...",...,"(transporte mantenimiento, transporte servicio...","(0.710953414440155, 0.6618167757987976, 0.6518...","(de agua, de de, potabilizada, Aguas residua...","(0.7279173731803894, 0.7838726043701172, 0.792...","(adecuación transición, adecuación ineficienci...","(0.7431526780128479, 0.686488151550293, 0.6975...","(reciclar reciclada, reciclar reciclado, reuti...","(0.7133514881134033, 0.7682274580001831, 0.726...","(construcciones plantas, construcciones edific...","(0.6657102108001709, 0.6868520975112915, 0.740..."
17,Bono_Verde_de_Bancoldex_Framework.pdf,"(renovable sostenible, renovable energético, r...","(0.6984525918960571, 0.6615170836448669, 0.650...","(red red, acondicionar facilitar, acondicionar...","(0.7134368419647217, 0.652474045753479, 0.6647...","(contaminación implementación, contaminación t...","(0.7019962668418884, 0.6985132098197937, 0.746...","(. económicos, . residuales, . energéticas, . ...","(0.8585679531097412, 0.8812421560287476, 0.868...","(biodiversidad sostenible, biodiversidad mitig...",...,"(transporte almacenamiento, transporte transpo...","(0.7192397713661194, 1.0, 0.6558911204338074, ...","(de agua, de de, saneamiento implementación, s...","(0.6710147857666016, 0.7838726043701172, 0.748...","(adecuación implementación, adecuación transic...","(0.8621118664741516, 0.7431526780128479, 0.783...","(reutilizar almacenamiento, reutilizar facilitar)","(0.6537311673164368, 0.6510095000267029)","(construcciones adecuaciones, construcciones e...","(0.8131966590881348, 0.793316125869751, 0.7187..."
18,Green_Bonds_Framework_Athon_2020.pdf,"(energia energia, bioenergia energia, potência...","(0.9084944128990173, 0.7116448879241943, 0.657...","(eficiência operação, eficiência necessidade, ...","(0.6674121618270874, 0.7167710661888123, 0.657...",(resíduos alimentos),(0.6529195308685303),(alimentares alimentos),(0.8313022255897522),"(biodiversidade socioambientais, biodiversidad...",...,"(transporte equipamentos, transporte equipamen...","(0.6563118696212769, 0.7077468633651733, 0.748...","(saneamento socioambientais, saneamento planej...","(0.6705000996589661, 0.7468856573104858, 0.665...","(adaptação construção, adaptação implementação)","(0.6819092035293579, 0.7532346844673157)",(),(),"(construções comunidades, construções construç...","(0.7177586555480957, 0.7227913737297058, 0.695..."