In [11]:
import openpyxl
import pandas as pd

In [2]:
bond_data = pd.read_excel(io='/Users/elisabethwatson/Documents/GitHub/Applied-data-sci-cert-project-Oct25-Watson/bondsAllocsJune7.xls', sheet_name='bondsJune7', usecols="A:N,V:AB,AG:AI")
bond_df = pd.DataFrame(bond_data)
bond_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 286 entries, 0 to 285
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Handle                   286 non-null    str
 1   is_in_allocs             286 non-null    bool
 2   pipeline_devlt           286 non-null    bool
 3   is_green                 286 non-null    bool
 4   eval_pop                 286 non-null    object
 5   testing_refine_pop       286 non-null    bool
 6   out_of_scope             286 non-null    object
 7   Link                     286 non-null    str
 8   Handle.1                 286 non-null    str
 9   ISIN                     240 non-null    str
 10  FIGI                     117 non-null    str
 11  CUSIP                    20 non-null     str
 12  Ticker                   109 non-null    str
 13  Name                     286 non-null    str
 14  Bond theme               286 non-null    str
 15  Issuer name              286 non-null    str
 16  Issuer type              286 non-null    str
 17  Issuer jurisdiction      286 non-null    str
 18  PDF name                 137 non-null    str
 19  Framework link           206 non-null    str
 20  sustainability report    195 non-null    str
 21  Bond currency            286 non-null    str
 22  Volume in bond currency  264 non-null    float64
 23  Volume in USD            264 non-null    float64
dtypes: bool(4), float64(2), object(2), str(16)
memory usage: 152.5+ KB

In [3]:
bond_df.head()

,Handle,is_in_allocs,pipeline_devlt,is_green,eval_pop,testing_refine_pop,out_of_scope,Link,Handle.1,ISIN,...,Bond theme,Issuer name,Issuer type,Issuer jurisdiction,PDF name,Framework link,sustainability report,Bond currency,Volume in bond currency,Volume in USD
0,9bd98e9cc0fd42a69775ddbd0c63147a,True,False,True,TRUE - Wave 2,False,False,https://www.greenbondtransparency.com/bond-inf...,9bd98e9cc0fd42a69775ddbd0c63147a,BRERENDBS073,...,green,Total Eren,Non-Financial Corporate,Brazil,NaN,Google gemini: Framework report issued duering...,Only at the parent level - would need to detec...,BRL,280000000.0,6.515264e+07
1,e6bb16f3d1e04ba789445370e5e99dc0,False,False,True,False,True,TRUE - No Docs,https://www.greenbondtransparency.com/bond-inf...,e6bb16f3d1e04ba789445370e5e99dc0,ARENEY560035,...,Green,360 Energy Solar S.A.,Non-Financial Corporate,Argentina,NaN,NaN,NaN,USD,60000000.0,6.000000e+07
2,82f9c056cca1404e906b6d3270884a77,False,False,True,False,True,False,https://www.greenbondtransparency.com/bond-inf...,82f9c056cca1404e906b6d3270884a77,PAL3009913J3,...,Green,Corporaci√≥n Interamericana para el Financiami...,Financial Corporate,Panama,CIFI_Green_Bond_Framework,https://www.greenbondtransparency.com/download...,4d55cd98379640de90be2eb2fa9aba1f,USD,2000000.0,2.000000e+06
3,3e001fbc60b6457dbbb4e67ee69152c0,True,True,True,False,False,False,https://www.greenbondtransparency.com/bond-inf...,3e001fbc60b6457dbbb4e67ee69152c0,CL0002521988,...,green,Aguas Andinas,Non-Financial Corporate,Chile,Green_social_bond_framework_series_ad_ae_2019,https://www.greenbondtransparency.com/download...,44e38dbb4e334294b5534acaf9930631,CLF,2000000.0,8.150633e+07
4,85ffe90464964adb84185c436e607c2f,False,False,False,False,False,True,https://www.greenbondtransparency.com/bond-inf...,85ffe90464964adb84185c436e607c2f,BRSCDILFI4Y4,...,Sustainability,Banco Cooperativo Sicredi S.A.,Financial Corporate,Brazil,NaN,https://www.greenbondtransparency.com/download...,3335c7c5d57a40b1a9abcb760293f7c1,BRL,572400000.0,1.111262e+08

In [4]:
alloc_data = pd.read_excel(io='/Users/elisabethwatson/Documents/GitHub/Applied-data-sci-cert-project-Oct25-Watson/bondsAllocsJune7.xls', sheet_name='allocationsJune7', usecols="A:AA")
alloc_df = pd.DataFrame(alloc_data)
alloc_df_ICMA = alloc_df[alloc_df['nomenclature'] == 'ICMA Green Bonds Principles Project Categories']
alloc_df_ICMA.info()

<class 'pandas.DataFrame'>
Index: 1002 entries, 1 to 2273
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   is_in_allocs                   975 non-null    float64
 1   pipeline_devlt                 975 non-null    float64
 2   is_green                       975 non-null    float64
 3   eval_pop                       975 non-null    object
 4   testing_refine_pop             975 non-null    float64
 5   out_of_scope                   975 non-null    object
 6   PDF name                       975 non-null    object
 7   ISIN                           975 non-null    object
 8   FIGI                           975 non-null    object
 9   Ticker                         975 non-null    object
 10  bond_handle                    1002 non-null   str
 11  bond_name                      1002 non-null   str
 12  nomenclature                   1002 non-null   str
 13  category                       1002 non-null   str
 14  subcategory                    1002 non-null   str
 15  project                        1002 non-null   str
 16  location                       1002 non-null   str
 17  date_allocation                1002 non-null   datetime64[us]
 18  date_disbursement              1000 non-null   datetime64[us]
 19  allocation_currency            1002 non-null   str
 20  allocated_allocation_currency  1002 non-null   float64
 21  disbursed_allocation_currency  1000 non-null   float64
 22  bond_currency                  1002 non-null   str
 23  disbursed_bond_currency        1000 non-null   float64
 24  disbursed_usd                  1000 non-null   float64
 25  refinancing                    1002 non-null   bool
 26  cofinancing_percentage         834 non-null    float64
dtypes: bool(1), datetime64[us](2), float64(9), object(6), str(9)
memory usage: 381.6+ KB

In [5]:
alloc_df_ICMA.head()

,is_in_allocs,pipeline_devlt,is_green,eval_pop,testing_refine_pop,out_of_scope,PDF name,ISIN,FIGI,Ticker,...,date_allocation,date_disbursement,allocation_currency,allocated_allocation_currency,disbursed_allocation_currency,bond_currency,disbursed_bond_currency,disbursed_usd,refinancing,cofinancing_percentage
1,1.0,0.0,1.0,False,0.0,TRUE - No Docs,page not found on gbtp,COB07CB00587,0,0,...,2016-12-05,2016-12-05,COP,5.271430e+09,5.271430e+09,COP,5.271430e+09,1722104.0,True,0.92
3,1.0,0.0,1.0,False,0.0,TRUE - No Docs,page not found on gbtp,COB07CB00587,0,0,...,2016-12-05,2016-12-05,COP,2.488157e+09,2.488157e+09,COP,2.488157e+09,812847.0,True,0.92
5,1.0,0.0,1.0,False,0.0,TRUE - No Docs,page not found on gbtp,COB07CB00587,0,0,...,2016-12-05,2016-12-05,COP,7.917525e+10,7.917525e+10,COP,7.917525e+10,25865474.0,True,0.92
7,1.0,0.0,1.0,False,0.0,TRUE - No Docs,page not found on gbtp,COB07CB00587,0,0,...,2016-12-05,2016-12-05,COP,8.515670e+10,8.515670e+10,COP,8.515670e+10,27819531.0,True,0.92
9,1.0,0.0,1.0,False,0.0,TRUE - No Docs,page not found on gbtp,COB07CB00587,0,0,...,2016-12-05,2016-12-05,COP,2.137972e+10,2.137972e+10,COP,2.137972e+10,6984461.0,True,0.92

In [6]:
alloc_df_ICMA['nomenclature'].unique()

<ArrowStringArray>
['ICMA Green Bonds Principles Project Categories']
Length: 1, dtype: str

In [7]:
alloc_df_ICMA['category'].unique()

<ArrowStringArray>
[         'Renewable energy',      'Water and wastewater',
         'Energy efficiency',      'Clean transportation',
           'Green buildings',                     'Other',
  'Environmental management',                 'Pollution',
                    'Social',     'Eco-efficient economy',
 'Climate change adaptation']
Length: 11, dtype: str

In [40]:
# five populations: 1) eval W1 popn, 2) training rpts in alloc, 3) training rpts not in alloc, 4) eval W2 popn, 5) out of scope
# start with training rpts in alloc
# determine data structure for ground truth data


trng_rpts_in_alloc_cond = (alloc_df_ICMA['eval_pop'] == False) & (alloc_df_ICMA['out_of_scope'] == False)
trng_rpts_in_alloc = alloc_df_ICMA[trng_rpts_in_alloc_cond]
trng_rpts_in_alloc['PDF name and categories'] = trng_rpts_in_alloc['PDF name'] + '    >>>     ' + trng_rpts_in_alloc['category']
tria_output = trng_rpts_in_alloc['PDF name and categories'].unique()
tria_output

<ArrowStringArray>
[   'Green_social_bond_framework_series_ad_ae_2019    >>>     Water and wastewater',
        'Green_social_bond_framework_series_ad_ae_2019    >>>     Renewable energy',
                       'SONDA_S_A__GREEN_BOND_FRAMEWORK    >>>     Green buildings',
                     'Green_Bonds_Framework_Athon_2020    >>>     Renewable energy',
 'Climate_Bond_Framework_of_E1_SUBHOLDING_S_A__in_2021    >>>     Renewable energy',
            'Coca-Cola_FEMSA_Green_Bond_Framework    >>>     Eco-efficient economy',
             'Coca-Cola_FEMSA_Green_Bond_Framework    >>>     Water and wastewater',
                 'Coca-Cola_FEMSA_Green_Bond_Framework    >>>     Renewable energy']
Length: 8, dtype: str

In [9]:
# next go to training reports not in alloc

trng_rpts_not_in_alloc_cond = (bond_df['eval_pop'] == False) & (bond_df['out_of_scope'] == False) & (bond_df['is_in_allocs'] == False)
trng_rpts_not_in_alloc = bond_df[trng_rpts_not_in_alloc_cond]
trng_rpts_not_in_alloc
trng_rpts_not_in_alloc['PDF name'].unique()

<ArrowStringArray>
[                                                          'CIFI_Green_Bond_Framework',
                                                        'CABEI´s_Green_Bond_Framework',
                                                 'BTG_Sustainable_Financing_Framework',
                                                        'Genneia_Green_Bond_Framework',
                                                    'Chile_Sustainable_Bond_Framework',
                                                               'Bono_Azul_-_Framework',
                                                               'Cartilla_Bonos_Verdes',
                                                 'FS_Green_Bond_Framework_-_July_2021',
                                                          'CAF’s_GREEN_BOND_FRAMEWORK',
    'Reference_Framework_Of_Green_Social_Sustainable_Bonds_of_Bogota_Capital_District',
                       'BTG_Pactual_Green,_Social_and_Sustainable_Financing_Framework',
                             'Marco_de_referencia_de_bono_verde_Coopeguanacaste,_R_L_',
                                                      'ILAP_Green_Financing_Framework',
                                                                'Green_Bond_Framework',
                                                'EGE_Haina_Green_Securities_Framework',
                                                   'Genneia_Green_Financing_Framework',
                                                           'CADU_GREEN_BOND_FRAMEWORK',
                                                 'Bci_Sustainable_Financing_Framework',
                                             'FS_Green_Bond_Framework_-_November_2020',
                                                        'Sicredi_Green_Bond_Framework',
                           'Marco_de_Referencia_del_Bono_Verde_de_la_Ciudad_de_Mexico',
                                                  'Nacional_Financiera_Green_Bond_MXN',
                                                  'Nacional_Financiera_Green_Bond_USD',
                                                      'Green_Bond_Financing_Framework',
 'Marco_de_Uso_de_Fondo_para_la_Emision_de_Bonos_Verdes,_Sociales_o_Sostenibles_BDP_I',
                                             'Green_Bond_Framework_of_Banco_Guayaquil',
                           'Marco_de_referencia_de_Bonos_Verdes_Soberanos_de_Colombia',
                                                     'Marco_de_Gestión_de_Bono_Verde',
                                                  'Green_Finance_Framework_Interchile',
                                                   'Bono_Verde_de_Bancoldex_Framework',
                                                 'Marco_de_referencia_Bono_Verde_BPDC']
Length: 31, dtype: str

In [12]:

gt_train_rpts = pd.read_excel(io='/Users/elisabethwatson/Documents/GitHub/Applied-data-sci-cert-project-Oct25-Watson/bondsAllocsJune7.xlsx', sheet_name='ground_truth_train', dtype={'pdfname': str, "gt_source": str, "ES_0_percent": bool, "ES_100_percent": bool, "ES_partial": bool, "number_of_cats": int})
gtt_df = pd.DataFrame(gt_train_rpts)
gtt_df

,pdfname,gt_source,ES_0_percent,ES_100_percent,ES_partial,number_of_cats
0,Bci_Sustainable_Financing_Framework,manual,False,False,True,6
1,Bono_Azul_-_Framework,manual,True,False,False,0
2,Bono_Verde_de_Bancoldex_Framework,manual,False,False,True,5
3,"BTG_Pactual_Green,_Social_and_Sustainable_Fina...",manual,False,False,True,7
4,BTG_Sustainable_Financing_Framework,manual,False,False,True,13
5,CABEI_Green_Bond_Framework,manual,False,False,True,4
6,CADU_GREEN_BOND_FRAMEWORK,manual,True,False,False,0
7,CAFs_GREEN_BOND_FRAMEWORK,manual,False,False,True,6
8,Cartilla_Bonos_Verdes,manual,False,False,True,8
9,Chile_Sustainable_Bond_Framework,manual,False,False,True,17
10,CIFI_Green_Bond_Framework,manual,False,False,True,3
11,Climate_Bond_Framework_of_E1_SUBHOLDING_S_A__i...,alloc data table,False,True,False,0
12,Coca-Cola_FEMSA_Green_Bond_Framework,alloc data table,False,False,True,3
13,EGE_Haina_Green_Securities_Framework,manual,False,True,False,0
14,FS_Green_Bond_Framework_-_July_2021,manual,False,False,True,2
15,FS_Green_Bond_Framework_-_November_2020,manual,False,False,True,2
16,Genneia_Green_Bond_Framework,manual,False,True,False,0
17,Genneia_Green_Financing_Framework,manual,False,True,False,0
18,Green_Bond_Financing_Framework,manual,True,False,False,0
19,Green_Bond_Framework,manual,False,True,False,0
20,Green_Bond_Framework_of_Banco_Guayaquil,manual,False,False,True,4
21,Green_Bonds_Framework_Athon_2020,alloc data table,False,True,False,0
22,Green_Finance_Framework_Interchile,manual,False,False,True,2
23,Green_social_bond_framework_series_ad_ae_2019,alloc data table,False,False,True,2
24,ILAP_Green_Financing_Framework,manual,False,True,False,0
25,ISA_CTM_FRAMEWORK,manual,False,False,True,2
26,Marco_de_Gestion_de_Bono_Verde,manual,False,True,False,0
27,Marco_de_referencia_Bono_Verde_BPDC,manual,False,False,True,8
28,Marco_de_referencia_de_bono_verde_Coopeguanaca...,manual,False,True,False,0
29,Marco_de_referencia_de_Bonos_Verdes_Soberanos_...,manual,False,False,True,8
30,Marco_de_Referencia_del_Bono_Verde_de_la_Ciuda...,manual,False,False,True,8
31,Marco_de_Uso_de_Fondo_para_la_Emision_de_Bonos...,manual,False,False,True,11
32,Nacional_Financiera_Green_Bond_MXN,manual,False,True,False,0
33,Nacional_Financiera_Green_Bond_USD,manual,False,True,False,0
34,Reference_Framework_Of_Green_Social_Sustainabl...,manual,True,False,False,0
35,Sicredi_Green_Bond_Framework,manual,False,False,True,2
36,SONDA_S_A__GREEN_BOND_FRAMEWORK,alloc data table,True,False,False,0