### Create confusion matrix and box plots for predictions from nlp adn ground truth data

In [1]:
import pandas as pd

In [3]:
gt_train_rpts = pd.read_excel(io='/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/bondsAllocsJune7.xlsx', sheet_name='ground_truth_train', dtype={'pdfname': str, "gt_source": str, "ES_0_percent": bool, "ES_100_percent": bool, "ES_partial": bool, "number_of_cats": int})
gt_train_df = pd.DataFrame(gt_train_rpts)
gt_train_df

,pdfname,gt_source,ES_0_percent,ES_100_percent,ES_partial,number_of_cats
0,Bci_Sustainable_Financing_Framework,manual,False,False,True,6
1,Bono_Azul_-_Framework,manual,True,False,False,0
2,Bono_Verde_de_Bancoldex_Framework,manual,False,False,True,5
3,"BTG_Pactual_Green,_Social_and_Sustainable_Fina...",manual,False,False,True,7
4,BTG_Sustainable_Financing_Framework,manual,False,False,True,13
5,CABEI_Green_Bond_Framework,manual,False,False,True,4
6,CADU_GREEN_BOND_FRAMEWORK,manual,True,False,False,0
7,CAFs_GREEN_BOND_FRAMEWORK,manual,False,False,True,6
8,Cartilla_Bonos_Verdes,manual,False,False,True,8
9,Chile_Sustainable_Bond_Framework,manual,False,False,True,17
10,CIFI_Green_Bond_Framework,manual,False,False,True,3
11,Climate_Bond_Framework_of_E1_SUBHOLDING_S_A__i...,alloc data table,False,True,False,0
12,Coca-Cola_FEMSA_Green_Bond_Framework,alloc data table,False,False,True,3
13,EGE_Haina_Green_Securities_Framework,manual,False,True,False,0
14,FS_Green_Bond_Framework_-_July_2021,manual,False,False,True,2
15,FS_Green_Bond_Framework_-_November_2020,manual,False,False,True,2
16,Genneia_Green_Bond_Framework,manual,False,True,False,0
17,Genneia_Green_Financing_Framework,manual,False,True,False,0
18,Green_Bond_Financing_Framework,manual,True,False,False,0
19,Green_Bond_Framework,manual,False,True,False,0
20,Green_Bond_Framework_of_Banco_Guayaquil,manual,False,False,True,4
21,Green_Bonds_Framework_Athon_2020,alloc data table,False,True,False,0
22,Green_Finance_Framework_Interchile,manual,False,False,True,2
23,Green_social_bond_framework_series_ad_ae_2019,alloc data table,False,False,True,2
24,ILAP_Green_Financing_Framework,manual,False,True,False,0
25,ISA_CTM_FRAMEWORK,manual,False,False,True,2
26,Marco_de_Gestion_de_Bono_Verde,manual,False,True,False,0
27,Marco_de_referencia_Bono_Verde_BPDC,manual,False,False,True,8
28,Marco_de_referencia_de_bono_verde_Coopeguanaca...,manual,False,True,False,0
29,Marco_de_referencia_de_Bonos_Verdes_Soberanos_...,manual,False,False,True,8
30,Marco_de_Referencia_del_Bono_Verde_de_la_Ciuda...,manual,False,False,True,8
31,Marco_de_Uso_de_Fondo_para_la_Emision_de_Bonos...,manual,False,False,True,11
32,Nacional_Financiera_Green_Bond_MXN,manual,False,True,False,0
33,Nacional_Financiera_Green_Bond_USD,manual,False,True,False,0
34,Reference_Framework_Of_Green_Social_Sustainabl...,manual,True,False,False,0
35,Sicredi_Green_Bond_Framework,manual,False,False,True,2
36,SONDA_S_A__GREEN_BOND_FRAMEWORK,alloc data table,True,False,False,0

In [4]:
pred_train_rpts = pd.read_csv('/Users/elisabethwatson/Documents/GitHub/ADSCert_project_Watson/Output_DataFrames/pred_train_rpts_V4.csv')
pred_train_df = pd.DataFrame(pred_train_rpts)
pred_train_df

,Unnamed: 0,pdfname,nlp_path,language,similarity_threshold,cleanup_threshold,ES_0_percent,ES_100_percent,ES_partial,number_of_cats
0,0,Climate_Bond_Framework_of_E1_SUBHOLDING_S_A__i...,UOP_section_true,EN,0.65,0.65,False,False,True,3
1,1,Chile_Sustainable_Bond_Framework,Table,EN,0.65,0.65,False,False,True,8
2,2,Genneia_Green_Financing_Framework,Table,EN,0.65,0.65,False,True,False,1
3,3,Marco_de_Uso_de_Fondo_para_la_Emision_de_Bonos...,Table,ES,0.65,0.65,False,True,False,1
4,4,Green_Bond_Framework,Table,PT,0.65,0.65,False,False,True,2
5,5,Green_Bond_Framework,Table,PT,0.65,0.65,False,False,True,2
6,6,Green_Bonds_Framework_Athon_2020,UOP_section_true,PT,0.65,0.65,False,False,True,9
7,7,Cartilla_Bonos_Verdes,UOP_section_true,ES,0.65,0.65,False,False,True,10
8,8,Bono_Azul_-_Framework,UOP_section_true,ES,0.65,0.65,True,False,False,5
9,9,Marco_de_referencia_de_bono_verde_Coopeguanaca...,UOP_section_true,ES,0.65,0.65,False,False,True,9
10,10,Marco_de_Referencia_del_Bono_Verde_de_la_Ciuda...,UOP_section_false,ES,0.65,0.65,False,False,True,10
11,11,Nacional_Financiera_Green_Bond_MXN,Table,ES,0.65,0.65,False,False,True,2
12,12,Marco_de_Gestión_de_Bono_Verde,Table,ES,0.65,0.65,False,True,False,1
13,13,Bono_Verde_de_Bancoldex_Framework,UOP_section_true,ES,0.65,0.65,False,False,True,10
14,14,Green_social_bond_framework_series_ad_ae_2019,Table,EN,0.65,0.65,True,False,False,2
15,15,ISA_CTM_FRAMEWORK,Table,EN,0.65,0.65,False,False,True,2
16,16,SONDA_S_A__GREEN_BOND_FRAMEWORK,UOP_section_true,EN,0.65,0.65,False,False,True,4
17,17,CIFI_Green_Bond_Framework,UOP_section_true,EN,0.65,0.65,False,False,True,4
18,18,BTG_Sustainable_Financing_Framework,UOP_section_true,EN,0.65,0.65,False,False,True,10
19,19,CABEI_Green_Bond_Framework,Table,EN,0.65,0.65,False,False,True,3
20,20,Genneia_Green_Bond_Framework,UOP_section_true,EN,0.65,0.65,False,False,True,3
21,21,FS_Green_Bond_Framework_-_July_2021,UOP_section_false,EN,0.65,0.65,False,False,True,7
22,22,CAFs_GREEN_BOND_FRAMEWORK,Table,EN,0.65,0.65,False,False,True,4
23,23,"BTG_Pactual_Green,_Social_and_Sustainable_Fina...",Table,EN,0.65,0.65,False,False,True,6
24,24,ILAP_Green_Financing_Framework,UOP_section_false,EN,0.65,0.65,False,False,True,5
25,25,EGE_Haina_Green_Securities_Framework,UOP_section_true,EN,0.65,0.65,False,False,True,4
26,26,CADU_GREEN_BOND_FRAMEWORK,UOP_section_false,EN,0.65,0.65,False,False,True,7
27,27,Bci_Sustainable_Financing_Framework,UOP_section_false,EN,0.65,0.65,False,False,True,7
28,28,FS_Green_Bond_Framework_-_November_2020,UOP_section_false,EN,0.65,0.65,False,False,True,7
29,29,Sicredi_Green_Bond_Framework,Table,EN,0.65,0.65,False,False,True,2
30,30,Nacional_Financiera_Green_Bond_USD,UOP_section_true,EN,0.65,0.65,False,True,False,1
31,31,Green_Bond_Financing_Framework,Table,EN,0.65,0.65,False,False,True,2
32,32,Green_Bond_Framework_of_Banco_Guayaquil,Table,EN,0.65,0.65,False,False,True,2
33,33,Marco_de_referencia_de_Bonos_Verdes_Soberanos_...,UOP_section_true,EN,0.65,0.65,False,False,True,10
34,34,Green_Finance_Framework_Interchile,Table,EN,0.65,0.65,False,False,True,3